; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-oled]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_protocol = esptool
lib_deps = 
	; adafruit/Adafruit SSD1306@^2.5.16
	olikraus/U8g2@^2.36.17
build_flags = 
	-DCORE_DEBUG_LEVEL=1
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DSCREEN_I2C_SDA=5
	-DSCREEN_I2C_SCL=6
	-DSCREEN_ADDRESS=0x3C
	-DSCREEN_WIDTH=72
	-DSCREEN_HEIGHT=40
